03 / 08 / 2024
- Please note, the data below is currently in the midst of being formatted.  The plan is to make this a reference table with team names, and corresponding playoff success by season.

In [125]:
import pandas as pd
import numpy as np

In [124]:
df_NHL_playoff_wins = pd.DataFrame([],index=['Anaheim Ducks','Arizona Coyotes','Boston Bruins','Buffalo Sabres',
                                            'Calgary Flames','Carolina Hurricanes','Chicago Blackhawks','Colorado Avalanche',
                                            'Columbus Blue Jackets','Dallas Stars','Detroit Red Wings','Edmonton Oilers',
                                            'Florida Panthers','Los Angeles Kings','Minnesota Wild','Montreal Canadiens',
                                            'Nashville Predators','New Jersey Devils','New York Islanders','New York Rangers',
                                            'Ottawa Senators','Philadelphia Flyers','Pittsburgh Penguins','San Jose Sharks',
                                            'Seattle Kraken','St. Louis Blues', 'Tampa Bay Lightning','Toronto Maple Leafs',
                                            'Vancouver Canucks','Vegas Golden Knights','Washington Capitals','Winnipeg Jets'])
df_NHL_playoff_wins

Empty DataFrame
Columns: []
Index: [Anaheim Ducks, Arizona Coyotes, Boston Bruins, Buffalo Sabres, Calgary Flames, Carolina Hurricanes, Chicago Blackhawks, Colorado Avalanche, Columbus Blue Jackets, Dallas Stars, Detroit Red Wings, Edmonton Oilers, Florida Panthers, Los Angeles Kings, Minnesota Wild, Montreal Canadiens, Nashville Predators, New Jersey Devils, New York Islanders, New York Rangers, Ottawa Senators, Philadelphia Flyers, Pittsburgh Penguins, San Jose Sharks, Seattle Kraken, St. Louis Blues, Tampa Bay Lightning, Toronto Maple Leafs, Vancouver Canucks, Vegas Golden Knights, Washington Capitals, Winnipeg Jets]

In [141]:
df23 = pd.read_csv('/Users/phil/Documents/Capstone/Data/NHL_playoffs_by_year/2023_NHL_playoffs.csv')

In [142]:
df23 = df23.loc[0:15,df23.columns.intersection(['Team','W'])]
df23.rename(columns={'Team':'Team','W':'2023'},inplace=True)
df23

                    Team  2023
0   Vegas Golden Knights  16.0
1       Florida Panthers  13.0
2           Dallas Stars  10.0
3    Carolina Hurricanes   8.0
4         Seattle Kraken   7.0
5        Edmonton Oilers   6.0
6    Toronto Maple Leafs   5.0
7      New Jersey Devils   5.0
8          Boston Bruins   3.0
9     Colorado Avalanche   3.0
10      New York Rangers   3.0
11    New York Islanders   2.0
12        Minnesota Wild   2.0
13     Los Angeles Kings   2.0
14   Tampa Bay Lightning   2.0
15         Winnipeg Jets   1.0

In [118]:
df22 = pd.read_csv('/Users/phil/Documents/Capstone/Data/NHL_playoffs_by_year/2022_NHL_playoffs.csv')

In [119]:
df22 = df22.loc[0:15,df22.columns.intersection(['Team','W'])]
df22.rename(columns={'Team':'Team','W':'2022'},inplace=True)
df22

                   Team  2022
0    Colorado Avalanche  16.0
1   Tampa Bay Lightning  14.0
2      New York Rangers  10.0
3       Edmonton Oilers   8.0
4   Carolina Hurricanes   7.0
5       St. Louis Blues   6.0
6        Calgary Flames   5.0
7      Florida Panthers   4.0
8         Boston Bruins   3.0
9     Los Angeles Kings   3.0
10  Toronto Maple Leafs   3.0
11         Dallas Stars   3.0
12  Pittsburgh Penguins   3.0
13       Minnesota Wild   2.0
14  Washington Capitals   2.0
15  Nashville Predators   0.0

In [78]:
df21 = pd.read_csv('/Users/phil/Documents/Capstone/Data/NHL_playoffs_by_year/2021_NHL_playoffs.csv')

In [115]:
df21 = df21.loc[0:15,df21.columns.intersection(['Team','W'])]
df21.rename(columns={'Team':'Team','W':'2021'},inplace=True)
df21

                    Team  2021
0    Tampa Bay Lightning  16.0
1     Montreal Canadiens  13.0
2     New York Islanders  11.0
3   Vegas Golden Knights  10.0
4     Colorado Avalanche   6.0
5          Boston Bruins   6.0
6    Carolina Hurricanes   5.0
7          Winnipeg Jets   4.0
8         Minnesota Wild   3.0
9    Toronto Maple Leafs   3.0
10      Florida Panthers   2.0
11   Pittsburgh Penguins   2.0
12   Nashville Predators   2.0
13   Washington Capitals   1.0
14       St. Louis Blues   0.0
15       Edmonton Oilers   0.0

In [79]:
df20 = pd.read_csv('/Users/phil/Documents/Capstone/Data/NHL_playoffs_by_year/2020_NHL_playoffs.csv')

In [113]:
df20 = df20.loc[0:23,df20.columns.intersection(['Team','W'])]
df20.rename(columns={'Team':'Team','W':'2020'},inplace=True)
df20

                     Team  2020
0     Tampa Bay Lightning  18.0
1            Dallas Stars  15.0
2      New York Islanders  13.0
3    Vegas Golden Knights  12.0
4     Philadelphia Flyers  10.0
5       Vancouver Canucks  10.0
6      Colorado Avalanche   9.0
7      Montreal Canadiens   5.0
8          Calgary Flames   5.0
9           Boston Bruins   5.0
10    Carolina Hurricanes   4.0
11        Arizona Coyotes   4.0
12     Chicago Blackhawks   4.0
13  Columbus Blue Jackets   4.0
14    Toronto Maple Leafs   2.0
15    Washington Capitals   2.0
16        St. Louis Blues   2.0
17    Nashville Predators   1.0
18          Winnipeg Jets   1.0
19         Minnesota Wild   1.0
20       Florida Panthers   1.0
21        Edmonton Oilers   1.0
22    Pittsburgh Penguins   1.0
23       New York Rangers   0.0

In [80]:
df19 = pd.read_csv('/Users/phil/Documents/Capstone/Data/NHL_playoffs_by_year/2019_NHL_playoffs.csv')

In [112]:
df19 = df19.loc[0:15,df19.columns.intersection(['Team','W'])]
df19.rename(columns={'Team':'Team','W':'2019'},inplace=True)
df19

                     Team  2019
0         St. Louis Blues  16.0
1           Boston Bruins  15.0
2         San Jose Sharks  10.0
3     Carolina Hurricanes   8.0
4      Colorado Avalanche   7.0
5            Dallas Stars   7.0
6   Columbus Blue Jackets   6.0
7      New York Islanders   4.0
8    Vegas Golden Knights   3.0
9     Toronto Maple Leafs   3.0
10    Washington Capitals   3.0
11    Nashville Predators   2.0
12          Winnipeg Jets   2.0
13         Calgary Flames   1.0
14    Pittsburgh Penguins   0.0
15    Tampa Bay Lightning   0.0

In [81]:
df18 = pd.read_csv('/Users/phil/Documents/Capstone/Data/NHL_playoffs_by_year/2018_NHL_playoffs.csv')

In [110]:
df18 = df18.loc[0:15,df18.columns.intersection(['Team','W'])]
df18.rename(columns={'Team':'Team','W':'2018'},inplace=True)
df18

                     Team  2018
0     Washington Capitals  16.0
1    Vegas Golden Knights  13.0
2     Tampa Bay Lightning  11.0
3           Winnipeg Jets   9.0
4     Nashville Predators   7.0
5         San Jose Sharks   6.0
6     Pittsburgh Penguins   6.0
7           Boston Bruins   5.0
8     Toronto Maple Leafs   3.0
9     Philadelphia Flyers   2.0
10     Colorado Avalanche   2.0
11  Columbus Blue Jackets   2.0
12         Minnesota Wild   1.0
13      New Jersey Devils   1.0
14      Los Angeles Kings   0.0
15          Anaheim Ducks   0.0

In [82]:
df17 = pd.read_csv('/Users/phil/Documents/Capstone/Data/NHL_playoffs_by_year/2017_NHL_playoffs.csv')

In [109]:
df17 = df17.loc[0:15,df17.columns.intersection(['Team','W'])]
df17.rename(columns={'Team':'Team','W':'2017'},inplace=True)
df17

                     Team  2017
0     Pittsburgh Penguins  16.0
1     Nashville Predators  14.0
2         Ottawa Senators  11.0
3           Anaheim Ducks  10.0
4         Edmonton Oilers   7.0
5     Washington Capitals   7.0
6         St. Louis Blues   6.0
7        New York Rangers   6.0
8         San Jose Sharks   2.0
9      Montreal Canadiens   2.0
10          Boston Bruins   2.0
11    Toronto Maple Leafs   2.0
12         Minnesota Wild   1.0
13  Columbus Blue Jackets   1.0
14         Calgary Flames   0.0
15     Chicago Blackhawks   0.0

In [83]:
df16 = pd.read_csv('/Users/phil/Documents/Capstone/Data/NHL_playoffs_by_year/2016_NHL_playoffs.csv')

In [108]:
df16 = df16.loc[0:15,df16.columns.intersection(['Team','W'])]
df16.rename(columns={'Team':'Team','W':'2016'},inplace=True)
df16

                   Team  2016
0   Pittsburgh Penguins  16.0
1       San Jose Sharks  14.0
2   Tampa Bay Lightning  11.0
3       St. Louis Blues  10.0
4          Dallas Stars   7.0
5   Nashville Predators   7.0
6   Washington Capitals   6.0
7    New York Islanders   5.0
8    Chicago Blackhawks   3.0
9         Anaheim Ducks   3.0
10       Minnesota Wild   2.0
11     Florida Panthers   2.0
12  Philadelphia Flyers   2.0
13     New York Rangers   1.0
14    Detroit Red Wings   1.0
15    Los Angeles Kings   1.0

In [84]:
df15 = pd.read_csv('/Users/phil/Documents/Capstone/Data/NHL_playoffs_by_year/2015_NHL_playoffs.csv')

In [107]:
df15 = df15.loc[0:15,df15.columns.intersection(['Team','W'])]
df15.rename(columns={'Team':'Team','W':'2015'},inplace=True)
df15

                   Team  2015
0    Chicago Blackhawks  16.0
1   Tampa Bay Lightning  14.0
2         Anaheim Ducks  11.0
3      New York Rangers  11.0
4   Washington Capitals   7.0
5    Montreal Canadiens   6.0
6        Calgary Flames   5.0
7        Minnesota Wild   4.0
8    New York Islanders   3.0
9     Detroit Red Wings   3.0
10      Ottawa Senators   2.0
11  Nashville Predators   2.0
12    Vancouver Canucks   2.0
13      St. Louis Blues   2.0
14  Pittsburgh Penguins   1.0
15        Winnipeg Jets   0.0

In [85]:
df14 = pd.read_csv('/Users/phil/Documents/Capstone/Data/NHL_playoffs_by_year/2014_NHL_playoffs.csv')

In [106]:
df14 = df14.loc[0:15,df14.columns.intersection(['Team','W'])]
df14.rename(columns={'Team':'Team','W':'2014'},inplace=True)
df14

                     Team  2014
0       Los Angeles Kings  16.0
1        New York Rangers  13.0
2      Chicago Blackhawks  11.0
3      Montreal Canadiens  10.0
4           Boston Bruins   7.0
5           Anaheim Ducks   7.0
6     Pittsburgh Penguins   7.0
7          Minnesota Wild   6.0
8      Colorado Avalanche   3.0
9     Philadelphia Flyers   3.0
10        San Jose Sharks   3.0
11           Dallas Stars   2.0
12  Columbus Blue Jackets   2.0
13        St. Louis Blues   2.0
14      Detroit Red Wings   1.0
15    Tampa Bay Lightning   0.0

In [86]:
df13 = pd.read_csv('/Users/phil/Documents/Capstone/Data/NHL_playoffs_by_year/2013_NHL_playoffs.csv')

In [105]:
df13 = df13.loc[0:15,df13.columns.intersection(['Team','W'])]
df13.rename(columns={'Team':'Team','W':'2013'},inplace=True)
df13

                   Team  2013
0    Chicago Blackhawks  16.0
1         Boston Bruins  14.0
2     Los Angeles Kings   9.0
3   Pittsburgh Penguins   8.0
4       San Jose Sharks   7.0
5     Detroit Red Wings   7.0
6       Ottawa Senators   5.0
7      New York Rangers   5.0
8         Anaheim Ducks   3.0
9   Toronto Maple Leafs   3.0
10  Washington Capitals   3.0
11      St. Louis Blues   2.0
12   New York Islanders   2.0
13       Minnesota Wild   1.0
14   Montreal Canadiens   1.0
15    Vancouver Canucks   0.0

In [87]:
df12 = pd.read_csv('/Users/phil/Documents/Capstone/Data/NHL_playoffs_by_year/2012_NHL_playoffs.csv')

In [104]:
df12 = df12.loc[0:15,df12.columns.intersection(['Team','W'])]
df12.rename(columns={'Team':'Team','W':'2012'},inplace=True)
df12

                   Team  2012
0         Boston Bruins  16.0
1     Vancouver Canucks  15.0
2   Tampa Bay Lightning  11.0
3       San Jose Sharks   9.0
4     Detroit Red Wings   7.0
5   Nashville Predators   6.0
6   Washington Capitals   4.0
7   Philadelphia Flyers   4.0
8   Pittsburgh Penguins   3.0
9    Chicago Blackhawks   3.0
10   Montreal Canadiens   3.0
11       Buffalo Sabres   3.0
12        Anaheim Ducks   2.0
13    Los Angeles Kings   2.0
14     New York Rangers   1.0
15      Phoenix Coyotes   0.0

In [88]:
df11 = pd.read_csv('/Users/phil/Documents/Capstone/Data/NHL_playoffs_by_year/2011_NHL_playoffs.csv')

In [103]:
df11 = df11.loc[0:15,df11.columns.intersection(['Team','W'])]
df11.rename(columns={'Team':'Team','W':'2011'},inplace=True)
df11

                   Team  2011
0         Boston Bruins  16.0
1     Vancouver Canucks  15.0
2   Tampa Bay Lightning  11.0
3       San Jose Sharks   9.0
4     Detroit Red Wings   7.0
5   Nashville Predators   6.0
6   Washington Capitals   4.0
7   Philadelphia Flyers   4.0
8   Pittsburgh Penguins   3.0
9    Chicago Blackhawks   3.0
10   Montreal Canadiens   3.0
11       Buffalo Sabres   3.0
12        Anaheim Ducks   2.0
13    Los Angeles Kings   2.0
14     New York Rangers   1.0
15      Phoenix Coyotes   0.0

In [89]:
df10 = pd.read_csv('/Users/phil/Documents/Capstone/Data/NHL_playoffs_by_year/2010_NHL_playoffs.csv')

In [102]:
df10 = df10.loc[0:15,df10.columns.intersection(['Team','W'])]
df10.rename(columns={'Team':'Team','W':'2010'},inplace=True)
df10

                   Team  2010
0    Chicago Blackhawks  16.0
1   Philadelphia Flyers  14.0
2    Montreal Canadiens   9.0
3       San Jose Sharks   8.0
4   Pittsburgh Penguins   7.0
5         Boston Bruins   7.0
6     Vancouver Canucks   6.0
7     Detroit Red Wings   5.0
8       Phoenix Coyotes   3.0
9   Washington Capitals   3.0
10      Ottawa Senators   2.0
11   Colorado Avalanche   2.0
12       Buffalo Sabres   2.0
13    Los Angeles Kings   2.0
14  Nashville Predators   2.0
15    New Jersey Devils   1.0

In [90]:
df09 = pd.read_csv('/Users/phil/Documents/Capstone/Data/NHL_playoffs_by_year/2009_NHL_playoffs.csv')

In [101]:
df09 = df09.loc[0:15,df09.columns.intersection(['Team','W'])]
df09.rename(columns={'Team':'Team','W':'2009'},inplace=True)
df09

                     Team  2009
0     Pittsburgh Penguins  16.0
1       Detroit Red Wings  15.0
2      Chicago Blackhawks   9.0
3     Carolina Hurricanes   8.0
4           Boston Bruins   7.0
5           Anaheim Ducks   7.0
6     Washington Capitals   7.0
7       Vancouver Canucks   6.0
8       New Jersey Devils   3.0
9        New York Rangers   3.0
10    Philadelphia Flyers   2.0
11         Calgary Flames   2.0
12        San Jose Sharks   2.0
13        St. Louis Blues   0.0
14     Montreal Canadiens   0.0
15  Columbus Blue Jackets   0.0

In [91]:
df08 = pd.read_csv('/Users/phil/Documents/Capstone/Data/NHL_playoffs_by_year/2008_NHL_playoffs.csv')

In [100]:
df08 = df08.loc[0:15,df08.columns.intersection(['Team','W'])]
df08.rename(columns={'Team':'Team','W':'2008'},inplace=True)
df08

                   Team  2008
0     Detroit Red Wings  16.0
1   Pittsburgh Penguins  14.0
2          Dallas Stars  10.0
3   Philadelphia Flyers   9.0
4       San Jose Sharks   6.0
5      New York Rangers   5.0
6    Montreal Canadiens   5.0
7    Colorado Avalanche   4.0
8        Calgary Flames   3.0
9         Boston Bruins   3.0
10  Washington Capitals   3.0
11       Minnesota Wild   2.0
12        Anaheim Ducks   2.0
13  Nashville Predators   2.0
14    New Jersey Devils   1.0
15      Ottawa Senators   0.0

In [92]:
df07 = pd.read_csv('/Users/phil/Documents/Capstone/Data/NHL_playoffs_by_year/2007_NHL_playoffs.csv')

In [99]:
df07 = df07.loc[0:15,df07.columns.intersection(['Team','W'])]
df07.rename(columns={'Team':'Team','W':'2007'},inplace=True)
df07

                   Team  2007
0         Anaheim Ducks  16.0
1       Ottawa Senators  13.0
2     Detroit Red Wings  10.0
3        Buffalo Sabres   9.0
4      New York Rangers   6.0
5       San Jose Sharks   6.0
6     New Jersey Devils   5.0
7     Vancouver Canucks   5.0
8          Dallas Stars   3.0
9        Calgary Flames   2.0
10  Tampa Bay Lightning   2.0
11       Minnesota Wild   1.0
12  Nashville Predators   1.0
13  Pittsburgh Penguins   1.0
14   New York Islanders   1.0
15    Atlanta Thrashers   0.0

In [93]:
df06 = pd.read_csv('/Users/phil/Documents/Capstone/Data/NHL_playoffs_by_year/2006_NHL_playoffs.csv')

In [98]:
df06 = df06.loc[0:15,df06.columns.intersection(['Team','W'])]
df06.rename(columns={'Team':'Team','W':'2006'},inplace=True)
df06

                       Team  2006
0       Carolina Hurricanes  16.0
1           Edmonton Oilers  15.0
2            Buffalo Sabres  11.0
3   Mighty Ducks of Anaheim   9.0
4           San Jose Sharks   6.0
5         New Jersey Devils   5.0
6           Ottawa Senators   5.0
7        Colorado Avalanche   4.0
8            Calgary Flames   3.0
9         Detroit Red Wings   2.0
10      Philadelphia Flyers   2.0
11       Montreal Canadiens   2.0
12      Nashville Predators   1.0
13      Tampa Bay Lightning   1.0
14             Dallas Stars   1.0
15         New York Rangers   0.0